version: '3.1'

services:
  backend:
    build: .
    restart: always
    volumes:
      - ./:/code
    env_file:
      - ./__docker_files__/.env.backend
    networks:
      - backend
    depends_on:
      - database # load after database init
  database:
    image: postgres
    restart: always
    expose:
      - 5432
    volumes:
      - ./__docker_files__/pgdata:/var/lib/postgresql/data
    env_file:
      - ./__docker_files__/.env.database
    networks:
      - backend


networks:
  frontend:
  backend: